### ISSUE TITLE
Add Travis.yml

### ISSUE THREAD

**Issue by Owanesh** [GasGang/vaporwavely-js#10]
## Idea of our library

Rewrite [This repo](https://github.com/Owanesh/vaporwavely) in javascript (vanilla) 🙌

## You can help us! 💪🏻
**Help us to write travis.yml file**
_We'll add badge into readme.md_

## How to run tests?
Run `yarn install` and `yarn test` to test.

**Comment by AlithAnar** [comment]
Will take this

**Comment by AlithAnar** [comment]
Done
