### ISSUE TITLE
Split core js in two files

### ISSUE THREAD

**Issue by Owanesh** [GasGang/vaporwavely-js#4]
## Idea of our library

Rewrite [This repo](https://github.com/Owanesh/vaporwavely) in javascript (vanilla) 🙌

## You can help us! 💪🏻
**Split core.js in two files**
[This file](https://github.com/GasGang/vaporwavely-js/blob/master/vaporwavely.js) contains resources like `dictionary` variable. We want manage that list in a separate file. 

**Can you help us?**
Work in a branch and open a pullrequest (link this issue in your PR message)

**Comment by kndarp** [comment]
Hi!
I'd like to help with this
